if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("PrivacyCheckupCometRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4747502321978956"}),null);
__d("PrivacyCheckupCometRootQuery$Parameters",["PrivacyCheckupCometRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PrivacyCheckupCometRootQuery_facebookRelayOperation"),metadata:{},name:"PrivacyCheckupCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PrivacyCheckupCometTextWithEntities_textWithEntities.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"PrivacyCheckupCometTextWithEntities_textWithEntities",selections:[{args:null,kind:"FragmentSpread",name:"CometTextWithEntitiesRelay_textWithEntities"}],type:"TextWithEntities",abstractKey:null};e.exports=a}),null);
__d("PrivacyCheckupCometTopicReviewMultiStepQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5272289392797644"}),null);
__d("PrivacyCheckupCometTopicReviewMultiStepQuery$Parameters",["PrivacyCheckupCometTopicReviewMultiStepQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PrivacyCheckupCometTopicReviewMultiStepQuery_facebookRelayOperation"),metadata:{},name:"PrivacyCheckupCometTopicReviewMultiStepQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometErrorLoggingWrapper.react",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=function(a){babelHelpers.inheritsLoose(b,a);function b(){return a.apply(this,arguments)||this}var c=b.prototype;c.componentDidCatch=function(a){this.props.loggingCallback(a);throw a};c.render=function(){var a=this.props.children;return a};return b}(a.PureComponent);g["default"]=b}),98);
__d("PrivacyCheckupCometRoot.entrypoint",["JSResourceForInteraction","PrivacyCheckupCometRootQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeProps;a=a.topicsCollectionID;return{queries:{topicsCollectionQueryReference:{parameters:b("PrivacyCheckupCometRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),topicsCollectionID:a}}}}},root:c("JSResourceForInteraction")("PrivacyCheckupCometRoot.react").__setRef("PrivacyCheckupCometRoot.entrypoint")};g["default"]=a}),98);
__d("PrivacyCheckupCometTextWithEntities.react",["CometInlineEntityRenderer","CometRelay","CometTextLink.react","CometTextWithEntitiesRelay.react","PrivacyCheckupCometTextWithEntities_textWithEntities.graphql","PrivacyCheckupLoggingContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react");function a(a){var e=d("CometRelay").useFragment(h!==void 0?h:h=b("PrivacyCheckupCometTextWithEntities_textWithEntities.graphql"),a.textWithEntities$key),f=function(b,e){var f=d("PrivacyCheckupLoggingContext").usePrivacyCheckupLoggingContext();if(e.url==null)return b;var g="bodyLink4";if(a.level!=null)switch(a.level){case 1:g="bodyLink1";break;case 2:g="bodyLink2";break;case 3:g="bodyLink3";break;case 4:g="bodyLink4";break}return i.jsx(c("CometTextLink.react"),{color:"blueLink",href:e.url,onClick:function(){f({event:"link_click",link:e.url})},target:"_blank",type:g,children:b})};return i.jsx(c("CometTextWithEntitiesRelay.react"),{renderers:{ExternalUrl:[f],Inline:[(f=a.inlineEntityRenderer)!=null?f:c("CometInlineEntityRenderer")]},textWithEntities:e})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);