if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("ProfileCometMentionsFeedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7065919906782951"}),null);
__d("ProfileCometMentionsFeedQuery$Parameters",["ProfileCometMentionsFeedQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometMentionsFeedQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometMentionsFeedQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometMentionsTabWithDeepDiveRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5411379732210370"}),null);
__d("ProfileCometMentionsTabWithDeepDiveRootQuery$Parameters",["ProfileCometMentionsTabWithDeepDiveRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometMentionsTabWithDeepDiveRootQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometMentionsTabWithDeepDiveRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometReviewsFeedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4818967741517647"}),null);
__d("ProfileCometReviewsFeedQuery$Parameters",["ProfileCometReviewsFeedQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometReviewsFeedQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometReviewsFeedQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometReviewsTabRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="3862521673825920"}),null);
__d("ProfileCometReviewsTabRootQuery$Parameters",["ProfileCometReviewsTabRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometReviewsTabRootQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometReviewsTabRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometProfilePlusVideosRootQuery$Parameters",["CometProfilePlusVideosRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfilePlusVideosRootQuery_facebookRelayOperation"),metadata:{},name:"CometProfilePlusVideosRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometMentionsTabWithDeepDiveRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometMentionsFeedQuery$Parameters","ProfileCometMentionsTabWithDeepDiveRootQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("ProfileCometMentionsTabWithDeepDiveRoot.react").__setRef("ProfileCometMentionsTabWithDeepDiveRouteRoot.entrypoint"),function(a){a=a.routeProps;var b=a.userID;a=a.viewerID;return{queries:{mentionsFeedQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometMentionsFeedQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"ProfileCometMentionsTabRoute",feedbackSource:0,feedLocation:"TIMELINE",privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"timeline",scale:d("WebPixelRatio").get(),sortBy:"MOST_RELEVANT",userID:String(b)||""}},mentionsTabRootQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometMentionsTabWithDeepDiveRootQuery$Parameters"),variables:{isViewingSelf:b===a,scale:d("WebPixelRatio").get(),userID:String(b)||""}}}}});g["default"]=a}),98);
__d("ProfileCometReviewsTabRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometReviewsFeedQuery$Parameters","ProfileCometReviewsTabRootQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("ProfileCometReviewsTabRoot.react").__setRef("ProfileCometReviewsTabRouteRoot.entrypoint"),function(a){a=a.routeProps.userID;return{queries:{reviewsFeedQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometReviewsFeedQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"ProfileCometReviewsTabRoute",feedbackSource:0,feedLocation:"PAGE_SURFACE_RECOMMENDATIONS",privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"timeline",scale:d("WebPixelRatio").get(),userID:String(a)||""}},reviewsTabRootQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometReviewsTabRootQuery$Parameters"),variables:{userID:String(a)||""}}}}});g["default"]=a}),98);
__d("CometProfilePlusVideosRoot.entrypoint",["CometProfilePlusVideosRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometProfileRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("CometProfilePlusVideosRoot.react").__setRef("CometProfilePlusVideosRoot.entrypoint"),function(a){var c;a=a.routeProps;var e=a.canViewerEditPage,f=a.isViewerCoreAppAdminNotLoggedIn,g=a.pageID;a=a.viewerID;return{extraProps:{canViewerEditPage:e,isViewerCoreAppAdminNotLoggedIn:f,pageID:(c=g)!=null?c:""},queries:{CometProfilePlusVideosRootQueryReference:{environmentProviderOptions:{actorID:a},parameters:b("CometProfilePlusVideosRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CometProfilePlusVideosRoot",displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedbackSource:86,feedLocation:"PROFILE_PLUS_TIMELINE",focusCommentID:null,pageID:g,scale:d("WebPixelRatio").get()*4,shouldLoadAdminControls:e||f,showReactions:!0,useDefaultActor:!1}}}}});g["default"]=a}),98);